redhat-performance/scale-ci-tripleo

- roles/scalelab-network/tasks/main.yml
It points to root since we start the playbook as root. This causes
failures when looking for the overcloudrc.
> Don't use ansible_env.HOME

- roles/overcloud-deploy/templates/overcloud-deploy.sh.j2
Based on https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/disable_telemetry.html
Untested.
> Disable telemetry during overcloud deployment.

- profiles/main.yml
- profiles/openshift-deploy.yml
- roles/undercloud-prepare-host/templates/undercloud.11.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.12.conf.j2
Use the ansible variable ntp_server in when setting up the undercloud. The value is set in openshift-deploy.yml and is read from an environment variable.
> Set the undercloud_ntp_server in the triple-o templates

- requirements-openshift-build.txt
Having the old repository caused a problem with the last deployment where the cidr ranges were not updated.
> Use the redhat-performance repository in the requirements file.

- roles/overcloud-deploy/templates/overcloud-deploy.sh.j2
Trying to disable telemetry by
openstack-tripleo-heat-templates/environments/disable-telemetry.yaml
did not work.  Use roles_data-notelem.yaml instead.
@mbruzek please merge once https://github.com/redhat-performance/openstack-templates/pull/19 is merged, thanks.
> Disabling telemetry using roles_data-notelem.yaml.

- roles/overcloud-deploy/templates/overcloud-deploy.sh.j2
This commit ensures that we pass the environmental file for disabling
notifications fro mthe various OpenStack services without which RabbitMQ
would be overwhelmed when telemetry is disabled.
Hence, when passing /home/stack/templates/roles_data-notelem.yaml we
also need to pass /home/stack/templates/disable-notifications.yaml to
the deploy command.
> Disable notifications

- profiles/openshift-deploy.yml
This PR is to start a discussion how the real problem can be fixed.  This PR only reverts the previous change to subnet_pool_start, which is very likely not a real solution.  There are conflicts between the FIP ranges and IPs allocated on the 3 controllers.  The controller conflicting IPs are are .8,  .10,  .13, but on the same network range as the FIP range. @mbruzek  PTAL
> Change subnet_pool_start due to conflict with controller IPs.

- profiles/openshift-staging.yml
The staging environment has 12 total 1029p machines. It is smaller than the normal scale-ci environment. So some values need to change in this profile to reflect the different number of machines.
> Adding a profile for the smaller staging environment.

- profiles/openshift-staging.yml
The staging environment needs different templates due to the networking difference and not having any 1029u machines.
This PR uses the new `openshift-scalelab-staging` templates.
> Making the staging script call the staging templates.

- profiles/openshift-staging.yml
- roles/overcloud-prepare-templates/tasks/main.yml
While reviewing the log of the latest deploy: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/scale-ci_install_staging_OpenStack/2/consoleFull
I found an unusual path in a task:
```
TASK [overcloud-prepare-templates : Copy over folder for this deployment] ******
task path: /home/slave5/workspace/scale-ci_install_staging_OpenStack/venv/usr/local/share/ansible/roles/overcloud-prepare-templates/tasks/main.yml:10
Thursday 05 April 2018  17:11:58 -0400 (0:00:00.757)       1:08:06.035 ******** 
changed: [b04-h02-1029p.rdu.openstack.engineering.redhat.com] => {"changed": true, "dest": "/home/stack/templates/", "src": "/home/slave5/workspace/scale-ci_install_staging_OpenStack/venv/playbooks/lookup('env','WORKSPACE')/templates/RDU-Scale/Ocata/openshift-scalelab-ci/"}
```
Can not …
> Fixing the template path errors and gateway address.

- profiles/openshift-deploy.yml
- profiles/openshift-staging.yml
- roles/undercloud-prepare-host/tasks/main.yml
With the new network environment in the staging area, it is no longer necessary to configure NAT to the external network, but it is still needed for the "normal" scale-ci environment at this time. Making it optional and configured by a variable.
> Making the NAT process optional.

- profiles/openshift-deploy.yml
This can be useful in the presence of failed hosts, so that the PRs do not need to be created all the time.  Ideally, I believe the final node could be derived from the number of available hosts in the JSON inventory file.
> Making the number of P1029 computes configurable.

- profiles/openshift-deploy.yml
- profiles/openshift-staging.yml
With a number of systems going bad we need to change these values regularly and I wanted to make them configurable with environment variables.
Note there is a change in one environment variable name from P1029COMPUTES to NUM_COMPUTE.
> Making the system numbers configurable via environment variables.

- roles/rebuild-undercloud/templates/toggle-rebuild.sh.j2
In staging we encountered a problem with this toggle-rebuild.sh script because `curl` does not return an error when HTTP authentication fails. This turned out to be a critical error and should have stopped the install process because jobs after that failed. 
Updating the script to return 1 when an error occurred.
> Making the script return 1 when an error occurred.

- roles/undercloud-install/tasks/main.yml
Keystone deployed as a singular process will bottleneck overcloud deployment in large enough environments, thus set to more processes.
> Adjust Keystone for faster deployment

- roles/undercloud-install/tasks/main.yml
Path is introduced in Ansible 2.4, but the job uses Ansible 2.3
> Ansible 2.3 lineinfile does not recognize path parameter

- roles/overcloud-deploy/tasks/main.yml
Duct tape for ostag
ostag requires openstacksdk==0.9.19
openstacksdk==0.9.19 requires os-client-config>=1.28.0
os-client-config>1.29.0 breaks ostag, so downgrade to 1.29.0
> Pin os-client-config in ostag venv

- roles/undercloud-prepare-host/tasks/main.yml
OpenStack networking is confusing enough, lets remove the QUADS validation vlans
to prevent confusion and potentially a vlan conflict in the future.
Addresses #34
> Clean up the scale lab validation vlans off the Undercloud Host

- roles/undercloud-prepare-host/templates/undercloud.10.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.11.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.12.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.13.conf.j2
This expands 10,11,12 OpenStack ctlplane Ip Address ranges for both the
introspection address pool and the overcloud DHCP/PXE pool.  Expanding
these pools will ensure we have plenty of address space as the scale of
the overcloud may increase in the future or if qnq-1 based clouds consume
more ctlplane addresses.
Commented out defaults are included to show difference between defaults and
adjusted values.  OSP 13 undercloud.conf already has a /16 configured.
> Expanding ctlplane ip address ranges

- roles/overcloud-prepare-templates/files/nic-configs/1029p-cephstorage.yaml
- roles/overcloud-prepare-templates/files/nic-configs/1029p-compute.yaml
- roles/overcloud-prepare-templates/files/nic-configs/1029p-controller.yaml
- roles/overcloud-prepare-templates/files/nic-configs/1029u-cephstorage.yaml
I found a few extras left over in the nic-config files that I cleaned up.  Also
these config files should work with both qnq0 and qnq1 lab switch configs.
> Clean up the 1029p and 1029u nic-configs

- profiles/main.yml
- profiles/openshift-deploy.yml
- profiles/openshift-small.yml
- profiles/openshift-staging.yml
- roles/undercloud-prepare-host/tasks/main.yml
- roles/undercloud-prepare-host/templates/undercloud.10.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.11.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.12.conf.j2
- roles/undercloud-prepare-host/templates/undercloud.13.conf.j2
Stack user password was being set incorrectly. Vars require further
organizing but lets just start by pruning whats not actually used
and is just cruft.
Lastly, lets keep commented vars in undercloud.conf so we can see what
was adjusted and what the default is.
> Remove unused vars, fix stack user password, undercloud.conf adjustments

- deploy-scalelab.yaml
- roles/rebuild-undercloud/tasks/main.yml
- roles/undercloud-prepare-host/tasks/main.yml
Do not gather facts on a machine about to be rebuilt. Exchange ssh key rather
than relaying on ssh passwords.
> Disable fact gather for rebuild and root ssh key exchange

- profiles/main.yml
- profiles/openshift-deploy.yml
- profiles/openshift-staging.yml
- roles/undercloud-install/tasks/main.yml
We can use this to stand up the staging environment and potentially scale ci
environment much faster without the use of introspection.
> Allow toggle to disable introspection completely

- profiles/main.yml
- profiles/openshift-deploy.yml
- profiles/openshift-staging.yml
- roles/undercloud-prepare-host/tasks/main.yml
I tested this in a small playbook. 
```yaml
---
- name: This tests the env fix
hosts: localhost
vars:
external_network_setup: "{{ lookup('env', 'OSP_EXTERNAL_NETWORK_SETUP')|default(0, true) }}"
tasks:
- name: Task to print stuff
debug:
var: external_network_setup
- name: Task to optionally skip
debug:
msg: "Run this task if the value is zero"
when: external_network_setup == "0"
```
> external_network_setup is a string compare against other strings.

- roles/overcloud-prepare-templates/files/nic-configs/private/1029p-cephstorage.yaml
- roles/overcloud-prepare-templates/files/nic-configs/private/1029p-compute.yaml
- roles/overcloud-prepare-templates/files/nic-configs/private/1029p-controller.yaml
- roles/overcloud-prepare-templates/files/nic-configs/private/1029u-cephstorage.yaml
This is the result of discussion on networking and attempting to deploy in the cloud03 environment.
Fixes slow connection to ceph and makes the templates all refer to the nics in numerical order to make them easier to compare and possibly work with qnq0 since the nics match on other systems.
> Changed order of nics to match, disabled unused nics, for consistency.

- roles/overcloud-prepare-templates/files/nic-configs/private/1029p-compute.yaml
- roles/overcloud-prepare-templates/files/nic-configs/public/1029p-compute.yaml
br-int name is reserved for the OpenStack integration bridge
Through a series of edits to improve nic-configs (Public/Private implementation) regarding the length of OVS bridge names, bridge names were reduced since long bridges never get created.  Bridges were also named based off the "type" of network traffic expected (Ex. tenant traffic - br-tenant).  Incidently a bridge was named br-int inadvertently since internal api traffic was placed on a sole bridge (no longer carrying external traffic) Thus the bridge name changed from br-ex to br-internal and then shorterned to br-int.  Since this occured on a compute node where br-int is essential we ended up with a switching loop in the correct conditions.  In an ideal world, tripleo should not have validated or deployed a nic-config with a …
> Do not use "br-int"

- roles/overcloud-prepare-templates/files/args.yaml
- roles/overcloud-prepare-templates/files/compute-params.yaml
- roles/overcloud-prepare-templates/files/first-boot.yaml
- roles/overcloud-prepare-templates/files/roles_data-notelem.yaml
- roles/overcloud-prepare-templates/files/scheduler-hints.yaml
Since we have an LTA on 1029p machines, we no longer currently need composable roles for
compute nodes.
> Adjustments to templates to remove 1029p composable role

- roles/overcloud-prepare-templates/files/roles_data-notelem.yaml
- roles/overcloud-prepare-templates/tasks/main.yml
- roles/overcloud-prepare-templates/templates/scheduler-hints.yaml.j2
- roles/undercloud-install/tasks/main.yml
- vars/deploy.yml
OSP12/13 uses "ComputeSchedulerHints"
OSP10/11 uses "NovaComputeSchedulerHints"
This patch templates those out per version.
We also use the typical "novacompute" vs "compute-" which is the default. We
should not need to set the hostname default format either.
> Fix compute node pinning

- install-browbeat.yaml
Use bootstrap.py for speed up.  We need this (https://review.openstack.org/#/c/579656/)
to be merged before merging this.  The speed up for staging is 2.6s vs 73s.  The gain
is larger for larger clouds (scale-ci)
> Speedup Browbeat install with bootstrap.py

- install-browbeat.yaml
Stack user requires the ssh key to be exchanged with the Undercloud machine. In
this case that turns out to be the same machine as the stack user is on.  The
previous generate_tripleo_hostfile.sh script did this for us.
> Minor fix for using bootstrap.py

- roles/overcloud-prepare-templates/tasks/main.yml
- roles/overcloud-prepare-templates/templates/create_public_cluster_network.sh.j2
- roles/scalelab-network/tasks/main.yml
The past few OpenStack deploys have failed, with manual intervention needed to complete the install. The network creation steps are the last things the automation performs and we always have to enter these commands by hand.
This change writes a script with the network creation commands early so we don't have to manually recreate the individual commands.
> Writing a script to create networks, and call the script.

- roles/overcloud-deploy/files/pin.py
- roles/overcloud-deploy/tasks/main.yml
- roles/overcloud-deploy/templates/pin-nodes.sh.j2
- roles/undercloud-introspection/tasks/main.yml
- vars/deploy.yml
ostag requires several fixes to work correctly with OSP13, rather
than manage the dependencies across several repos, it is easier to
create a python script that interacts directly with the Ironic API
in order to pin nodes as we need.  There are also some Ansible
logic issues fixed such as variables not evaluating correctly
without a filter (Ex. |bool)
> Changes for OSP13

- roles/overcloud-prepare-templates/templates/1029p-storage-environment.yaml.j2
- roles/overcloud-prepare-templates/templates/1029u-storage-environment.yaml.j2
There is a bug with Ceph Ansible in that pg/pgp count
should be adjust post overcloud deployed.  In this case
we set the pg/pgp count very low and will add post
overcloud deploy workaround to tune the pg/pgp count to
the correct size.
> Adjust Ceph pg count very low for OSP13

- install-browbeat.yaml
Provide a newer openstacksdk vs the default tripleo installed openstacksdk
> OSP13 needs updated openstacksdk for bootstrap.py in Browbeat

- deploy-scalelab.yaml
- roles/post-deploy/tasks/main.yml
- roles/scalelab-network/tasks/main.yml
- roles/undercloud-prepare-host/tasks/main.yml
- vars/deploy.yml
This is the work to add some post deployment tasks to configure ceph pg and pgp numbers.
This required adding the overcloud machines to the in memory host list.
Renamed the `scalelab-network` role to `post-deploy` but github did not pick that up.
> Renaming a role to perform post deploy tasks.

- roles/undercloud-prepare-host/tasks/main.yml
- roles/undercloud-prepare-host/templates/motd.j2
- vars/deploy.yml
Using the bash code from `clean-interfaces.sh` so we don't rely on a file that is outside of this process to clean VLANs.
Also adding a template for the Message of the Day (motd). To give the users information about the environment.
> Changing the vlan clean procedure and adding motd template.

- roles/overcloud-prepare-templates/files/controller-params.yaml
In the staging environment, we have a limited set of compute nodes
in which it is possible to encounter a race condition where as an
instance requiring PCI passthrough NVMe hits MaxRetriesExceeded.
Raising the number of possible attempts in order to increase likely
hood of successful instance booting in the staging environment with
PCI passthrough.
> Raise Nova Max Scheduler Attempts

- roles/overcloud-deploy/tasks/main.yml
tmux window ordering was mixed up due to window index used
> Tweak the install tmux

- README.md
- update-cluster-motd.yaml
- vars/update-cluster-motd.yml
In hindsight, lets just choose a message rather than User/Email so we can state the cluster is free after usage or other scenarios too.
> Update motd with a message rather than just User and Email

- roles/overcloud-prepare-templates/files/nic-configs/13/public/1029p-controller.yaml
- roles/overcloud-prepare-templates/tasks/main.yml
- roles/overcloud-prepare-templates/templates/create_external_cluster_network.sh.j2
- roles/overcloud-prepare-templates/templates/create_public_cluster_network.sh.j2
- roles/overcloud-prepare-templates/templates/post_deploy_workarounds.sh.j2
- roles/post-deploy/tasks/main.yml
- vars/deploy.yml
Latest run on the new lab means we no longer need an external vlan id
> Changing public nic-configs for the new lab switch setup
